version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: List project files
          command: ls -R .

      - run:
          name: Build Docker image
          command: |
            docker info
            docker build -t $DOCKER_USERNAME/currencyfront:$CIRCLE_SHA1 .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/currencyfront:$CIRCLE_SHA1

workflows:
  version: 2
  sample-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
